### PR TITLE
Pr/14

### PR DESCRIPTION
**Pull request by mroberge**
Alright- I'm a little confused, but I think I am merging my changes to your pull request #14.
This adds some tests and some docs.

### CODE REVIEW

**Comment by mroberge** [comment]
I made a mistake and made a pull request to the wrong place. I'm going to go back and take this branch, "[mroberge:Pr/14](https://github.com/mroberge/hydrofunctions/tree/pr/14)" and create a new pull request into mroberge:Develop.  I will then try to get rid of this pull request.

Sorry for the confusion. I wanted to add some tests to your pull request before I merged it with Develop.

One thing that we should do in the future is to create a new branch off of Develop every time we try to add a new feature. Then I can merge your requests, add whatever, then merge the branch into develop.

**Comment by jdhughes-dev** [comment]
I just made a pull request with a few new tests and improved doc strings. I was confused as well. Will make new feature branches in the future to merge. Sorry if I messed anything up.

**Comment by mroberge** [comment]
I just merged everything into mroberge:Develop.  I think everything looks great. I think the more I mess around with git the better I get at it, so I view all of this confusion as learning taking place. 

I think I am going to bump the version number up and then merge everything to Master and hopefully these changes will deploy to PyPI.

**Comment by jdhughes-dev** [comment]
Great.

**Pull request closed without merging**
